import {
  UserProfile,
  FlightInfo,
  ItineraryItem,
  HotelItem,
  RestaurantItem,
  ChatMessage,
  DuffelOffer,
  GolfCourseItem,
  PassengerDoc,
} from './types';

export const initialProfile: UserProfile = {
  name: 'RBS (Roberto Bernardo Sanchez)',
  vipStatus: 'Estatus VIP Principal Activo',
  email: 'rbs@aeroguard.vip',
  avatarUrl:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDZPMlJySwm8uW5JeIwMSOsdXywYnPSL_yzPjPua2OsnLvFYMOj6CFVmY6xgtsPb9Xlvr2S_xiN704JyUeXiQjlDnEPKTKpCn7At2Nt3WyKAuIMLl-dcNSnLFb8RNcfz6NZ5P_LaCH9zPcrHzTQqINCymchHtPkRkoQsHRFs_bQWovaxXOqDHQRGkiLHYwifgrDIUPx8uE_K7disHoUum1p07RcWogR1MqwSwC48XkhBruI_OM7RPjGGw',
  passportExp: '12/2028',
  visas: ['US (B1/B2)', 'Schengen'],
  credentialStatus: 'Vigente',
  preferredSeat: 'Pasillo (Frente)',
  favoriteAirlines: ['Oneworld', 'Star Alliance'],
  hotelChains: ['Marriott', 'Four Seasons'],
  dietaryRequirements: 'Sin Gluten',
  emergencyContactsCount: 2,
  locationSharingActive: true,
  flightAlerts: true,
  globalSecurityAlerts: true,
  promotions: false,
};

export const currentFlight: FlightInfo = {
  flightNumber: 'AM 408',
  seat: '2A',
  classType: 'Business',
  originCode: 'MEX',
  originCity: 'Ciudad de México',
  destinationCode: 'JFK',
  destinationCity: 'Nueva York',
  departureTime: '10:30 AM EST',
  arrivalTime: '03:45 PM EDT',
  remainingTime: '2h 15m',
  status: 'En Vuelo',
  gate: 'T4 - G28',
  securityNote:
    'Equipo de escolta en posición JFK T4. Protocolo de extracción rápida confirmado.',
  gateChangeNote:
    'Nueva puerta asignada para llegada: T4 - G28. Vehículo ejecutivo reasignado a nueva terminal.',
  aircraftType: 'Boeing 787-9 Dreamliner',
  airline: 'Aeroméxico VIP',
  priceUsd: 2850,
  duffelOfferId: 'off_0000A1b2C3d4E5f6G7',
  altitudeFt: 38000,
  speedKmh: 890,
};

export const upcomingFlight: FlightInfo = {
  flightNumber: 'AM 404',
  seat: '1K',
  classType: 'First Class',
  originCode: 'MEX',
  originCity: 'Ciudad de México',
  destinationCode: 'JFK',
  destinationCity: 'Nueva York',
  departureTime: '19:45',
  arrivalTime: '00:15',
  remainingTime: 'En espera de abordaje',
  status: 'A tiempo',
  gate: 'G42',
  securityNote:
    'Conductor VIP asignado llegará 30 minutos antes a la entrada principal.',
  aircraftType: 'Gulfstream G650ER',
  airline: 'AeroGuard FBO Private',
  priceUsd: 14200,
  duffelOfferId: 'off_0000Z9y8X7w6V5u4T3',
};

export const sampleDuffelOffers: DuffelOffer[] = [
  {
    id: 'off_0001_duffel_mex_jfk',
    airlineName: 'Aeroméxico Premier VIP',
    airlineLogo: '✈️',
    flightNumber: 'AM 408',
    aircraft: 'Boeing 787-9 Dreamliner',
    originCode: 'MEX',
    originCity: 'Ciudad de México',
    destinationCode: 'JFK',
    destinationCity: 'Nueva York',
    departureTime: '10:30 AM',
    arrivalTime: '03:45 PM',
    duration: '4h 15m',
    stops: 0,
    priceUsd: 2850,
    classType: 'First Class',
    baggageIncluded: '3 Maletas de 32kg + Carga VIP',
    loungeAccess: true,
    helipadTransferAvailable: true,
    securityStatus: 'Verificación Táctica AeroGuard',
  },
  {
    id: 'off_0002_duffel_netjets_teb',
    airlineName: 'NetJets Private Charter FBO',
    airlineLogo: '🛩️',
    flightNumber: 'NJ 882',
    aircraft: 'Bombardier Global 7500',
    originCode: 'MEX',
    originCity: 'Toluca / CDMX FBO',
    destinationCode: 'TEB',
    destinationCity: 'Teterboro Executive NY',
    departureTime: '12:00 PM',
    arrivalTime: '05:00 PM',
    duration: '4h 00m',
    stops: 0,
    priceUsd: 18500,
    classType: 'VIP Private Jet FBO',
    baggageIncluded: 'Sin Límite - Cabina Personalizada',
    loungeAccess: true,
    helipadTransferAvailable: true,
    securityStatus: 'Escolta Táctica en Pista Privada',
  },
  {
    id: 'off_0003_duffel_british_lhr',
    airlineName: 'British Airways First Class',
    airlineLogo: '🇬🇧',
    flightNumber: 'BA 242',
    aircraft: 'Airbus A350-1000',
    originCode: 'MEX',
    originCity: 'Ciudad de México',
    destinationCode: 'LHR',
    destinationCity: 'Londres Heathrow',
    departureTime: '09:15 PM',
    arrivalTime: '02:30 PM (+1)',
    duration: '10h 15m',
    stops: 0,
    priceUsd: 6400,
    classType: 'First Class',
    baggageIncluded: '4 Maletas + Fast Track Escort',
    loungeAccess: true,
    helipadTransferAvailable: true,
    securityStatus: 'Fast Track Diplomatic Clearance',
  },
  {
    id: 'off_0004_duffel_emirates_mad',
    airlineName: 'Emirates First Class Suite',
    airlineLogo: '🇦🇪',
    flightNumber: 'EK 256',
    aircraft: 'Boeing 777-300ER',
    originCode: 'MIA',
    originCity: 'Miami International',
    destinationCode: 'MAD',
    destinationCity: 'Madrid Barajas FBO',
    departureTime: '07:30 PM',
    arrivalTime: '10:15 AM (+1)',
    duration: '8h 45m',
    stops: 0,
    priceUsd: 7900,
    classType: 'First Class',
    baggageIncluded: 'Suite Privada + Chauffeur Directo',
    loungeAccess: true,
    helipadTransferAvailable: true,
    securityStatus: 'Control de Seguridad de Cero Espera',
  },
];

export const sampleGolfCourses: GolfCourseItem[] = [
  {
    id: 'g1',
    name: 'Liberty National Golf Club',
    destinationCity: 'Nueva York',
    destinationCode: 'JFK',
    rating: 4.9,
    holes: 18,
    par: 72,
    yardage: 7358,
    slopeRating: '151 / 76.5',
    distanceFromCity: '12 km del Manhattan Financial Center',
    greenFeeUsd: 1200,
    helipadAccess: true,
    securityRating: 'Perímetro Biométrico Estricto',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBC2lM8pZ81vD6Q_2aO2o_dO3r-JbB-vV33q_6g7C2p-fC0H2P1i7rQ0f_NqB8aJ7qY_X_4b3m12-5q-34p0_yO2w3e5r1t-2y3u4i5o6p',
    description:
      'Exclusivo campo championship a orillas del río Hudson con vistas espectaculares a la Estatua de la Libertad y el Skyline de NY. Helipuerto privado en instalaciones.',
    handicapLimit: 18,
    caddieAvailable: true,
    dressCode: 'Etiqueta PGA Tradicional (Polo metido, bermuda o pantalón de vestir)',
  },
  {
    id: 'g2',
    name: 'Shinnecock Hills Golf Club',
    destinationCity: 'Nueva York / Hamptons',
    destinationCode: 'JFK',
    rating: 5.0,
    holes: 18,
    par: 70,
    yardage: 7440,
    slopeRating: '153 / 77.2',
    distanceFromCity: 'Vuelo en Helicóptero 25 min desde TEB/JFK',
    greenFeeUsd: 1800,
    helipadAccess: true,
    securityRating: 'Acceso Privado para Socios e Invitados VIP',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCyjqiQX8wswjjWLC0ipTIIF0P2y5GhIZt_Dw3h-hkbWBJ1BrSYFVD7m6TxtwXIby7dnWfpZT-DopYh_ARw_YNVx6aW-CRrCsyNc2dEAEhdmSAqutOKLv4GH0_dpKqcku7-1uj-hH5jHGClJTBAOnYwg68qD7K9ZFdFAwQLuUIeSO_gZp9aKmtqPEwhKBzyrMQODdY-j5WlUjlCD8lqpOCumAbFmmN7vHL-Iqq7L2JoUPJZewt9Z_j-pw',
    description:
      'Sede legendaria de múltiples US Open. Diseño links estadounidense puro con fairways ondeantes y verdes súper rápidos. Experiencia caddie de élite.',
    handicapLimit: 14,
    caddieAvailable: true,
    dressCode: 'Soft spikes únicamente, vestimenta rigurosa de golf',
  },
  {
    id: 'g3',
    name: 'Club de Golf Chapultepec',
    destinationCity: 'Ciudad de México',
    destinationCode: 'MEX',
    rating: 4.9,
    holes: 18,
    par: 71,
    yardage: 7345,
    slopeRating: '142 / 74.8',
    distanceFromCity: 'A 15 min de Polanco / Lomas de Chapultepec',
    greenFeeUsd: 650,
    helipadAccess: true,
    securityRating: 'Control de Acceso Blindado AeroGuard',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAyrdCoL0uxxueBxkCfZN8a8RgaplBfrQKDFIi33Y5v3WT-P6ZGwQ7qjlGhziZDayPfM-kUvsGqRPXT03nFiZcoXFwlRf4S0xUim16mZE5ARQQ1_69LlDfEzhORZkuwLQS8mwLgD7bDHKTBL6UlT-ucQ67S3pRmZ7iR3Jhsl7iFXwAsr4ae9egWMT0yf0e8tfkclsof3458xcpCtslnAuseAu0PEyjnJsnPmhKldZ77qmmJfstxqCTTmA',
    description:
      'Sede del World Golf Championships (WGC-Mexico Championship). Fairways arbolados a más de 2,200 m de altitud para máxima distancia de bola.',
    handicapLimit: 20,
    caddieAvailable: true,
    dressCode: 'Polo con cuello y pantalón formal de golf',
  },
  {
    id: 'g4',
    name: 'Trump National Doral Blue Monster',
    destinationCity: 'Miami',
    destinationCode: 'MIA',
    rating: 4.8,
    holes: 18,
    par: 72,
    yardage: 7590,
    slopeRating: '146 / 76.0',
    distanceFromCity: 'A 10 min de MIA International Airport FBO',
    greenFeeUsd: 950,
    helipadAccess: true,
    securityRating: 'Seguridad Privada 24/7',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuB8YJOiZBYEVhSLqIY62BUcqoOsqt5O90BQcJhPd5wqYzcPBFo6R6s7gk20mdMivuAFBxff_-kCccZMudumwvXrNewuUQpH1ZROgr2Qo7OUFTdrwhQhvd9ea1rvTtPzmBViLR-77JtRU_hnEzUTPmnYFzS_mVJ8ECvRkudba-KNi2lmwJPHcOY_MxCuFYYlcE25hRSc4bGDkDPnmcYSyP3pCmaTuUUwicdLISa0GgTz88Lo5BZGNulk-w',
    description:
      'El famoso "Blue Monster" desafía a los mejores golfistas del mundo con sus míticos obstáculos de agua en el hoyo 18.',
    handicapLimit: 24,
    caddieAvailable: true,
    dressCode: 'Vestimenta de golf estándar de alta gama',
  },
  {
    id: 'g5',
    name: 'Real Club La Moraleja',
    destinationCity: 'Madrid',
    destinationCode: 'MAD',
    rating: 4.9,
    holes: 18,
    par: 72,
    yardage: 7220,
    slopeRating: '138 / 74.0',
    distanceFromCity: 'A 10 min del Aeropuerto de Barajas FBO',
    greenFeeUsd: 550,
    helipadAccess: true,
    securityRating: 'Zona Privada Residencial de Máxima Seguridad',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBJ3XmPm8WdQPddUW0Bb_nZo1qvJT5pIxaLNIsIIBIoYL9NT7QxlHnTJUJ7nCVeYanki2SHFbge2b_9pmVuAd1vvjWWUmJbYhkYhMXEIlkp93YNi_d2rYR0L1-UmU4wpYhkczJgJjDCdRJkR2dM3exgvVUU9sfLs5M1OT1pydMEMq4h7cdnGzKANtRb2EqerwIJUdPjz2L_abiRNlHj22Q0dOUvzL2724xfjODjFFZNmyfL0f-NusQS_g',
    description:
      'Diseñado por Jack Nicklaus, uno de los complejos de golf más exclusivos de Europa con 4 campos de 18 hoyos e instalaciones VIP.',
    handicapLimit: 22,
    caddieAvailable: true,
    dressCode: 'Elegancia clásica europea',
  },
];

export const samplePassengers: PassengerDoc[] = [
  {
    id: 'p1_rbs',
    name: 'RBS (Roberto Bernardo Sanchez)',
    role: 'Principal (Líder de Grupo / C-Suite)',
    passportNumber: 'MEX-98124501',
    passportCountry: 'México 🇲🇽',
    passportExpDate: '15/12/2028',
    daysToPassportExp: 862,
    visaType: 'B1/B2 US Visa & Schengen',
    visaStatus: 'Válida',
    estaOrSchengenStatus: 'Aprobado',
    biometricClearance: 'Aprobado AeroGuard',
    dietaryOrMedical: 'Sin Gluten / Grupo O+',
    overallStatus: 'Completo',
    isFamilyRbs: true,
    familyRelationship: 'Principal (RBS)',
    sourceSheetUrl: 'https://docs.google.com/spreadsheets/d/1RBS_Familia_Docs_2026/edit',
    lastSyncedFromSheets: 'Hoy, 10:30 AM (Google Sheets Live)',
  },
  {
    id: 'p2_rbs',
    name: 'Sofía Sanchez de RBS',
    role: 'Esposa del Principal',
    passportNumber: 'MEX-87239102',
    passportCountry: 'México 🇲🇽',
    passportExpDate: '20/04/2027',
    daysToPassportExp: 257,
    visaType: 'B1/B2 US Visa & Schengen Global',
    visaStatus: 'Válida',
    estaOrSchengenStatus: 'Aprobado',
    biometricClearance: 'Aprobado AeroGuard',
    dietaryOrMedical: 'Vegetariana / A+',
    overallStatus: 'Completo',
    isFamilyRbs: true,
    familyRelationship: 'Esposa de RBS',
    sourceSheetUrl: 'https://docs.google.com/spreadsheets/d/1RBS_Familia_Docs_2026/edit',
    lastSyncedFromSheets: 'Hoy, 10:30 AM (Google Sheets Live)',
  },
  {
    id: 'p3_rbs',
    name: 'Mateo Sanchez (Hijo RBS)',
    role: 'Hijo Menor del Principal',
    passportNumber: 'MEX-55198203',
    passportCountry: 'México 🇲🇽',
    passportExpDate: '10/01/2027',
    daysToPassportExp: 157,
    visaType: 'B1/B2 US Visa (Infantil)',
    visaStatus: 'Válida',
    estaOrSchengenStatus: 'Aprobado',
    biometricClearance: 'Aprobado AeroGuard',
    dietaryOrMedical: 'Alergia a Nueces / O+',
    overallStatus: 'Completo',
    isFamilyRbs: true,
    familyRelationship: 'Hijo(a) de RBS',
    sourceSheetUrl: 'https://docs.google.com/spreadsheets/d/1RBS_Familia_Docs_2026/edit',
    lastSyncedFromSheets: 'Hoy, 10:30 AM (Google Sheets Live)',
  },
  {
    id: 'p4_rbs',
    name: 'Camila Sanchez (Hija RBS)',
    role: 'Hija del Principal',
    passportNumber: 'MEX-66291044',
    passportCountry: 'México 🇲🇽',
    passportExpDate: '05/09/2026',
    daysToPassportExp: 30,
    visaType: 'B1/B2 US Visa',
    visaStatus: 'Válida',
    estaOrSchengenStatus: 'Aprobado',
    biometricClearance: 'Aprobado AeroGuard',
    dietaryOrMedical: 'Lactosa Free / B+',
    overallStatus: 'Atención Requerida',
    isFamilyRbs: true,
    familyRelationship: 'Hijo(a) de RBS',
    sourceSheetUrl: 'https://docs.google.com/spreadsheets/d/1RBS_Familia_Docs_2026/edit',
    lastSyncedFromSheets: 'Hoy, 10:30 AM (Google Sheets Live)',
  },
  {
    id: 'p5',
    name: 'Carlos Mendoza',
    role: 'Director Financiero (CFO)',
    passportNumber: 'MEX-44120934',
    passportCountry: 'México 🇲🇽',
    passportExpDate: '10/11/2026',
    daysToPassportExp: 96,
    visaType: 'B1/B2 US Visa',
    visaStatus: 'Válida',
    estaOrSchengenStatus: 'Aprobado',
    biometricClearance: 'Aprobado AeroGuard',
    dietaryOrMedical: 'Sin restricciones / B+',
    overallStatus: 'Atención Requerida',
    isFamilyRbs: false,
  },
  {
    id: 'p6',
    name: 'Capitán Elena Ruiz',
    role: 'Jefa de Escolta & Seguridad Corporativa',
    passportNumber: 'MEX-33019821',
    passportCountry: 'México 🇲🇽',
    passportExpDate: '08/08/2029',
    daysToPassportExp: 1098,
    visaType: 'A2 / B1 US Officer Visa',
    visaStatus: 'Válida',
    estaOrSchengenStatus: 'Aprobado',
    biometricClearance: 'Aprobado AeroGuard',
    dietaryOrMedical: 'Licencia Táctica Armas Vigente / O-',
    overallStatus: 'Completo',
    isFamilyRbs: false,
  },
];

export const initialItinerary: ItineraryItem[] = [
  {
    id: '1',
    day: 'Día 1 - 12 de Octubre',
    time: '08:00 AM',
    title: 'Vuelo Privado XB-VIP',
    subtitle: 'Terminal FBO, Ciudad de México',
    status: 'Seguro',
    type: 'flight',
    icon: 'flight_takeoff',
    completed: true,
  },
  {
    id: '2',
    day: 'Día 1 - 12 de Octubre',
    time: '02:30 PM (EST)',
    title: 'Traslado Blindado Teterboro',
    subtitle: 'Aeropuerto Teterboro (TEB) a Manhattan',
    status: 'Seguro',
    type: 'shuttle',
    icon: 'airport_shuttle',
    completed: true,
  },
  {
    id: '3',
    day: 'Día 1 - 12 de Octubre',
    time: '03:45 PM (EST)',
    title: 'Check-in: The Plaza Hotel',
    subtitle: '768 5th Ave, New York, NY 10019',
    status: 'Precaución Zonal',
    type: 'hotel',
    icon: 'hotel',
    completed: false,
  },
  {
    id: '4',
    day: 'Día 1 - 12 de Octubre',
    time: '05:30 PM (EST)',
    title: 'Reunión de Consejo Directivo',
    subtitle: 'Torre Financiera, Wall Street',
    status: 'Seguro',
    type: 'meeting',
    icon: 'business_center',
    completed: false,
  },
  {
    id: '5',
    day: 'Día 1 - 12 de Octubre',
    time: '08:00 PM (EST)',
    title: 'Cena Ejecutiva',
    subtitle: 'Le Bernardin, 155 W 51st St',
    status: 'Seguro',
    type: 'dinner',
    icon: 'restaurant',
    completed: false,
  },
  {
    id: '6',
    day: 'Día 2 - 13 de Octubre',
    time: '09:00 AM (EST)',
    title: 'Sesión de Golf VIP Championship',
    subtitle: 'Liberty National Golf Club - Tee Time Reservado',
    status: 'Seguro',
    type: 'golf',
    icon: 'sports_golf',
    completed: false,
  },
];

export const sampleHotels: HotelItem[] = [
  {
    id: 'h1',
    name: 'The Beekman',
    rating: 5.0,
    pricePerNight: 450,
    distance: 'A 400 m del punto de reunión',
    status: 'Zona segura',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAdHVCEkcDncS9X-iyJRw3YCbQYAkPj_WQ2phDsJ-RQJfWhtyk9U2el8IMLVrxg4GFqK9Jj31GWaGhd0sQZstpgCQ0V0F1gQg0dX8BfW1uP637jP5Km6vJv-c_8lNBfd2_4EqOnALZVqBAUmPUeqxMIoB7a_-tm0RfoYsX2qhunFSXwrgApPJQFHZevtyzyS3Jumkj3pQaAP6rCFGHLevjfQqXmWWYcwMik7sMCq3S_xH2gvCIYGO1uLQ',
    description:
      'Alojamiento boutique de 5 estrellas con estricto control de accesos y valet privado.',
  },
  {
    id: 'h2',
    name: 'Four Seasons Downtown',
    rating: 4.8,
    pricePerNight: 620,
    distance: 'A 650 m del punto de reunión',
    status: 'Zona segura',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuB8YJOiZBYEVhSLqIY62BUcqoOsqt5O90BQcJhPd5wqYzcPBFo6R6s7gk20mdMivuAFBxff_-kCccZMudumwvXrNewuUQpH1ZROgr2Qo7OUFTdrwhQhvd9ea1rvTtPzmBViLR-77JtRU_hnEzUTPmnYFzS_mVJ8ECvRkudba-KNi2lmwJPHcOY_MxCuFYYlcE25hRSc4bGDkDPnmcYSyP3pCmaTuUUwicdLISa0GgTz88Lo5BZGNulk-w',
    description:
      'Acceso directo a helipuerto y salones ejecutivos insonorizados.',
  },
  {
    id: 'h3',
    name: 'The Ritz-Carlton New York, NoMad',
    rating: 4.9,
    pricePerNight: 750,
    distance: 'A 1.2 km del punto de reunión',
    status: 'Recomendado VIP',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBJ3XmPm8WdQPddUW0Bb_nZo1qvJT5pIxaLNIsIIBIoYL9NT7QxlHnTJUJ7nCVeYanki2SHFbge2b_9pmVuAd1vvjWWUmJbYhkYhMXEIlkp93YNi_d2rYR0L1-UmU4wpYhkczJgJjDCdRJkR2dM3exgvVUU9sfLs5M1OT1pydMEMq4h7cdnGzKANtRb2EqerwIJUdPjz2L_abiRNlHj22Q0dOUvzL2724xfjODjFFZNmyfL0f-NusQS_g',
    description:
      'Suites con entrada blindada y protocolo personalizado de recepción.',
  },
];

export const sampleRestaurants: RestaurantItem[] = [
  {
    id: 'r1',
    name: 'El Cielo Elegante',
    distance: '1.2 km',
    priceRange: '$$$$',
    badge: 'Michelin 3',
    badgeType: 'michelin',
    description:
      'Cocina fusión de autor en un ambiente de extrema privacidad. Acceso discreto para clientes VIP disponible.',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDeeP205MDpGY2_QJlEhik_fFFYLTAnVOlRj_5u1E5TC-YadETKjVMk1TXpqnwQKgN9CMh8q8JG1FlUH1sQYI_QjUQaffKo6ve_IWHsm3aewWYJYFBulViHTZ3zNDiUPM6X2wa1t_ZLr1W-WhgpFxgODQaYWvCRjdWz3rgKJTdb--Z-zROhG6Rg-RWaHBtM_f2uUCYrUM5-dy7-VdzQOmnWae_ot-8AvDwbTDVz-CzG7J3hw9fR9xcOqw',
    privacyLevel: 'Extrema Privacidad',
  },
  {
    id: 'r2',
    name: 'Kuro Omakase',
    distance: '3.5 km',
    priceRange: '$$$$',
    badge: '5-Star',
    badgeType: 'star',
    description:
      'Experiencia íntima de 12 tiempos. Cuenta con salones privados insonorizados para negociaciones de alto nivel.',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuD3KyQpnzBwlArQSvOdKOPhm2mHbIOcqBsah-ST8IPRr8zGI64nPI3dULjEEMl6gmaaMPiBtpsFa9jll2lJBx3xpPiM9gPoay4_e4FnFPKhSma1rC0eHnVStAfHfR5qc2I6sGn0-wuNGOqavxuG0YmccB_p1CVVRZsE8CRon_vQiIPOGkNc2_wPlkd9hIim_VPohiBwn1v___yj7Wxyx3K_rmc_aO_cDwXjlr_F6o6rJInrxYOzykSC9w',
    privacyLevel: 'Salón Insonorizado',
  },
  {
    id: 'r3',
    name: 'Alta Vista',
    distance: '5.0 km',
    priceRange: '$$$$$',
    badge: 'Michelin 2',
    badgeType: 'michelin',
    description:
      'Vistas panorámicas inigualables. Seguridad perimetral reforzada y protocolo de llegada directo desde helipuerto.',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAyrdCoL0uxxueBxkCfZN8a8RgaplBfrQKDFIi33Y5v3WT-P6ZGwQ7qjlGhziZDayPfM-kUvsGqRPXT03nFiZcoXFwlRf4S0xUim16mZE5ARQQ1_69LlDfEzhORZkuwLQS8mwLgD7bDHKTBL6UlT-ucQ67S3pRmZ7iR3Jhsl7iFXwAsr4ae9egWMT0yf0e8tfkclsof3458xcpCtslnAuseAu0PEyjnJsnPmhKldZ77qmmJfstxqCTTmA',
    privacyLevel: 'Acceso Helipuerto',
  },
];

export const initialChatMessages: ChatMessage[] = [
  {
    id: 'm1',
    sender: 'agent',
    text: 'Buenas noches, Sr. Ejecutivo. Su reserva para cenar ha sido confirmada. He ajustado la ruta de su chofer para asegurar una llegada discreta.',
    time: '20:15',
  },
  {
    id: 'm2',
    sender: 'agent',
    text: '',
    time: '20:16',
    richCard: {
      type: 'reservation',
      title: 'Reserva Confirmada',
      subtitle: 'Le Bernardin',
      timeOrDetails: '21:00 hrs, Mesa Privada',
      imageUrl:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuBJ3XmPm8WdQPddUW0Bb_nZo1qvJT5pIxaLNIsIIBIoYL9NT7QxlHnTJUJ7nCVeYanki2SHFbge2b_9pmVuAd1vvjWWUmJbYhkYhMXEIlkp93YNi_d2rYR0L1-UmU4wpYhkczJgJjDCdRJkR2dM3exgvVUU9sfLs5M1OT1pydMEMq4h7cdnGzKANtRb2EqerwIJUdPjz2L_abiRNlHj22Q0dOUvzL2724xfjODjFFZNmyfL0f-NusQS_g',
      statusBadge: 'Status: Seguro',
    },
  },
  {
    id: 'm3',
    sender: 'user',
    text: 'Excelente. ¿Hay alguna novedad con los vuelos en vivo de Duffel o los campos de golf en NY?',
    time: '20:18',
  },
  {
    id: 'm4',
    sender: 'agent',
    text: 'He sincronizado los vuelos en vivo mediante la API de Duffel (Test Environment 9c4dd565ec8b149054303c0). Además, he reservado Tee-Time en Liberty National Golf Club con helipuerto privado y sincronizado el listado de Invitados VIP con Google Sheets.',
    time: '20:19',
  },
];

export const sampleGuests: PassengerDoc[] = [
  {
    id: 'g1_rbs',
    name: 'Ing. Alejandro Morales',
    role: 'Socio Comercial & Coinversionista',
    passportNumber: 'MEX-77182901',
    passportCountry: 'México 🇲🇽',
    passportExpDate: '18/11/2028',
    daysToPassportExp: 834,
    visaType: 'B1/B2 US Visa Business',
    visaStatus: 'Válida',
    estaOrSchengenStatus: 'Aprobado',
    biometricClearance: 'Aprobado AeroGuard',
    dietaryOrMedical: 'Dieta Kosher / Grupo A+',
    overallStatus: 'Completo',
    isGuest: true,
    guestCategory: 'Socio Comercial',
    invitedBy: 'RBS (Roberto Bernardo Sanchez)',
    sourceSheetUrl: 'https://docs.google.com/spreadsheets/d/1RBS_Invitados_VIP_2026/edit',
    lastSyncedFromSheets: 'Hoy, 10:35 AM (Google Sheets Live)',
  },
  {
    id: 'g2_rbs',
    name: 'Dra. Valeria Lindemann',
    role: 'Consultora Financiera Internacional',
    passportNumber: 'CHE-99201844',
    passportCountry: 'Suiza 🇨🇭',
    passportExpDate: '08/03/2027',
    daysToPassportExp: 214,
    visaType: 'ESTA USA & Schengen Free',
    visaStatus: 'Válida',
    estaOrSchengenStatus: 'Aprobado',
    biometricClearance: 'Aprobado AeroGuard',
    dietaryOrMedical: 'Sin restricciones / AB+',
    overallStatus: 'Completo',
    isGuest: true,
    guestCategory: 'Consultor Especial',
    invitedBy: 'RBS (Roberto Bernardo Sanchez)',
    sourceSheetUrl: 'https://docs.google.com/spreadsheets/d/1RBS_Invitados_VIP_2026/edit',
    lastSyncedFromSheets: 'Hoy, 10:35 AM (Google Sheets Live)',
  },
  {
    id: 'g3_rbs',
    name: 'Arch. Fernando Valdés',
    role: 'Director de Arquitectura & Real Estate',
    passportNumber: 'MEX-33829104',
    passportCountry: 'México 🇲🇽',
    passportExpDate: '12/09/2026',
    daysToPassportExp: 37,
    visaType: 'B1/B2 US Visa',
    visaStatus: 'Válida',
    estaOrSchengenStatus: 'Aprobado',
    biometricClearance: 'Aprobado AeroGuard',
    dietaryOrMedical: 'Pescetariano / O-',
    overallStatus: 'Atención Requerida',
    isGuest: true,
    guestCategory: 'Socio Comercial',
    invitedBy: 'RBS (Roberto Bernardo Sanchez)',
    sourceSheetUrl: 'https://docs.google.com/spreadsheets/d/1RBS_Invitados_VIP_2026/edit',
    lastSyncedFromSheets: 'Hoy, 10:35 AM (Google Sheets Live)',
  },
  {
    id: 'g4_rbs',
    name: 'Sra. Monique Dupont',
    role: 'Inversionista Capital Privado',
    passportNumber: 'FRA-88201923',
    passportCountry: 'Francia 🇫🇷',
    passportExpDate: '14/10/2029',
    daysToPassportExp: 1164,
    visaType: 'ESTA USA Active',
    visaStatus: 'Válida',
    estaOrSchengenStatus: 'Aprobado',
    biometricClearance: 'Aprobado AeroGuard',
    dietaryOrMedical: 'Champagne Brut / Vegan / A-',
    overallStatus: 'Completo',
    isGuest: true,
    guestCategory: 'Inversionista VIP',
    invitedBy: 'RBS (Roberto Bernardo Sanchez)',
    sourceSheetUrl: 'https://docs.google.com/spreadsheets/d/1RBS_Invitados_VIP_2026/edit',
    lastSyncedFromSheets: 'Hoy, 10:35 AM (Google Sheets Live)',
  },
];
